version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/chronolens
    steps:
      - checkout
      - run: ./gradlew check codeCoverageReport
      - store_test_results:
          path: build/reports/tests/unit-test/aggregated-results
      - store_artifacts:
          path: build/reports/tests/unit-test/aggregated-results
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  test:
    jobs:
      - test

