version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/chronolens
    steps:
      - checkout
      - run:
          name: Run tests and generate test and code coverage reports
          command: |
            ./gradlew check aggregateTestReport codeCoverageReport --continue
      - run:
          name: Upload code coverage report to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -f \
                build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
      - store_artifacts:
          path: build/reports/tests/unit-test/aggregated-results

workflows:
  test:
    jobs:
      - test

