version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/chronolens
    steps:
      - checkout
      - run:
          name: Test
          command: ./gradlew testAggregateTestReport --continue
      - run:
          name: Generate code coverage report
          command: ./gradlew testCodeCoverageReport --continue
      - store_artifacts:
          path: build/reports/tests/unit-test/aggregated-results
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  test:
    jobs:
      - test

